[phases.setup]
nixPkgs = ["nodejs-18_x", "nginx"]

[phases.install]
cmds = [
  "cd sendmenow",
  "npm install"
]

[phases.build]
cmds = [
  "cd sendmenow",
  "npm run build"
]

[start]
cmd = "nginx -g 'daemon off;' -c /app/sendmenow/nginx.conf"
